### ISSUE TITLE
MalformedURLException thrown when trying to construct URL with IPv6 addresses

### ISSUE THREAD

**Issue by ecprokop** [splunk/cloudfwd#27]
When hostname resolves to an IPv6 address, a MalformedURLException is thrown because we are not constructing the URL object properly (IPv6 address should be enclosed in brackets ([ ]) in the URL).

Splunk does not listen over IPv6 by default - we need to decide if we want to support this.

SEVERE: null
java.net.MalformedURLException: For input string: "0:0:0:0:0:0:1:8088"
	at java.net.URL.<init>(URL.java:627)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at com.splunk.cloudfwd.util.LoadBalancer.addChannel(LoadBalancer.java:142)
	at com.splunk.cloudfwd.util.LoadBalancer.createChannels(LoadBalancer.java:110)
	at com.splunk.cloudfwd.util.LoadBalancer.sendBatch(LoadBalancer.java:78)
	at com.splunk.cloudfwd.Connection.sendBatch(Connection.java:153)
	at com.splunk.cloudfwd.Connection.send(Connection.java:140)
	at AbstractConnectionTest.sendEvents(AbstractConnectionTest.java:99)
	at BatchedVolumeTest.sendJsonToEventsEndpointWithBuffering(BatchedVolumeTest.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

**Comment by ecprokop** [comment]
Fixed in https://github.com/splunk/cloudfwd/pull/76/files
